### ISSUE TITLE
55. CLI 설치

### ISSUE THREAD

**Issue by ihoneymon** [ihoneymon/translate-spring-boot-reference#41]

**Comment by helols** [comment]
스프링 부트 1.2.0 버전 맞지요 ? 
다는 확인 못해봤지만 CLI설치는 55가 아니라 54인것 같은데요. 
http://docs.spring.io/spring-boot/docs/1.2.0.RELEASE/reference/htmlsingle/#cli-installation

Part VII. Spring Boot CLI 요부분 발 번역해보고 있는데.. 문서를 제대로 보고 하는게 맞는지 확인차.. 질문 남겨봅니다..

**Comment by ihoneymon** [comment]
@helols 제가 기준으로 삼고 있는 것은 READEME.md 와 함께 있는  `Spring Boot Reference Guide.html` 파일이거든요. ^^; 저걸 처음 시작할 때에 내용이 살짝 추가된 것으로 보입니다.

**Comment by helols** [comment]
아아아.. 답변 감사드립니다. 저 html파일을 봐야겠네요 ㅎㅎ

On Wednesday, September 2, 2015, Kim Ji-Heon notifications@github.com
wrote:

> @helols https://github.com/helols 제가 기준으로 삼고 있는 것은 READEME.md 와 함께 있는 Spring
> Boot Reference Guide.html 파일이거든요. ^^; 저걸 처음 시작할 때에 내용이 살짝 추가된 것으로 보입니다.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ihoneymon/translate-spring-boot-reference/issues/41#issuecomment-137277078
> .

## 

/Yoon
